#!/usr/bin/env python3

import os
import sys
import json
import argparse
import json_minify
from urllib.request import urlopen

#
# Default Configuration File
#
DEFAULTS_FILENAME = '/lwa/software/defaults.json'

#
# Make sure shlQube.py is in our path
#
sys.path.append(os.path.dirname(DEFAULTS_FILENAME))
from shlQube import get_iceqube_status


HVAC_UNIT_ID = 1


def main(args):
    # Parse the config. file
    with open(args.config, 'r') as ch:
        config = json.loads(json_minify.json_minify(ch.read()))
        
    # Load in the IP address to use
    try:
        ip_address = config['hvac']['ip'][HVAC_UNIT_ID-1]
    except (KeyError, IndexError):
        raise RuntimeError(f"No configuration info. found for HVAC #{HVAC_UNIT_ID}")
        
    # Query the unit
    status = get_iceqube_status(ip_address)
    if status is None:
        print(f"compressor{HVAC_UNIT_ID}: disabled off")
    elif status['cooling']:
        print(f"compressor{HVAC_UNIT_ID}: enabled on")
    else:
        print(f"compressor{HVAC_UNIT_ID}: enabled off")


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=f"read the compressor status of IceQube HVAC #{HVAC_UNIT_ID}",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
        )
    parser.add_argument('-c', '--config', type=str, default=DEFAULTS_FILENAME,
                        help='name of the SHL configuration file to use')
    args = parser.parse_args()
    main(args)
