#!/usr/bin/env python3

import os
import sys
import json
import argparse
import json_minify
from urllib.request import urlopen

#
# Default Configuration File
#
DEFAULTS_FILENAME = '/lwa/software/defaults.json'


def main(args):
    # Parse the config. file
    with open(args.config, 'r') as ch:
        config = json.loads(json_minify.json_minify(ch.read()))
        
    # Load in the IP address to use
    try:
        ip_address = config['hvac']['ip'][0]
    except (KeyError, IndexError):
        raise RuntimeError("No configuration info. found for HVAC #%i" % 1)
        
    # Query the unit
    with urlopen(f"http://{ip_address}/ledstate.cgi", timeout=20) as uh:
        status = uh.read()
        status = status.decode()
        status = int(status)
        
        if status & 8:
            print('compressor1: enabled on')
        else:
            print('compressor1: enabled off')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='read the compressor status of the first IceQube HVAC unit',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
        )
    parser.add_argument('-c', '--config', type=str, default=DEFAULTS_FILENAME,
                        help='name of the SHL configuration file to use')
    args = parser.parse_args()
    main(args)
